-- Add Staff role and payslip management support

INSERT INTO role_definitions (role, label, permissions)
VALUES (
  'staff',
  'Staff',
  '{
    "dashboard": true,
    "calendar": false,
    "bookings": false,
    "bookingsConfirm": false,
    "bookingsDelete": false,
    "patients": false,
    "practice": false,
    "activity": false,
    "settings": true,
    "bookingsComplete": false,
    "manageUsers": false,
    "manageAvailability": false,
    "payslips": true,
    "managePayslips": false
  }'::jsonb
)
ON CONFLICT (role) DO UPDATE
SET
  label = EXCLUDED.label,
  permissions = EXCLUDED.permissions,
  updated_at = NOW();

-- Ensure every role definition has explicit payslip permissions
UPDATE role_definitions
SET
  permissions = jsonb_set(
    jsonb_set(
      COALESCE(permissions, '{}'::jsonb),
      '{payslips}',
      CASE
        WHEN role = 'staff' THEN 'true'::jsonb
        ELSE 'false'::jsonb
      END,
      true
    ),
    '{managePayslips}',
    CASE
      WHEN role = 'super_admin' THEN 'true'::jsonb
      ELSE 'false'::jsonb
    END,
    true
  ),
  updated_at = NOW();

CREATE TABLE IF NOT EXISTS staff_payslips (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_user_id INTEGER NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
  period_label TEXT NOT NULL,
  file_name TEXT NOT NULL,
  file_path TEXT NOT NULL UNIQUE,
  mime_type TEXT NOT NULL DEFAULT 'application/pdf',
  uploaded_by_user_id INTEGER REFERENCES admin_users(id) ON DELETE SET NULL,
  uploaded_by_username TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_staff_payslips_staff_user_id
  ON staff_payslips(staff_user_id);

CREATE INDEX IF NOT EXISTS idx_staff_payslips_created_at
  ON staff_payslips(created_at DESC);

ALTER TABLE staff_payslips ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all operations on staff_payslips" ON staff_payslips;
CREATE POLICY "Allow all operations on staff_payslips"
  ON staff_payslips
  FOR ALL
  USING (true);

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'staff-payslips',
  'staff-payslips',
  false,
  10485760,
  ARRAY['application/pdf', 'image/png', 'image/jpeg']
)
ON CONFLICT (id) DO NOTHING;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'Allow all operations on staff-payslips objects'
  ) THEN
    CREATE POLICY "Allow all operations on staff-payslips objects"
      ON storage.objects
      FOR ALL
      USING (bucket_id = 'staff-payslips')
      WITH CHECK (bucket_id = 'staff-payslips');
  END IF;
END $$;
